name: Vale Linter
description: The official GitHub Action for Vale -- install, manage, and run Vale with ease.
author: jdkato
branding:
  icon: check
  color: green

inputs:
  version:
    description: 'The Vale CLI version to install.'
    required: false
    default: 'latest'

  files:
    description: 'The files to lint: "all" or "<some_folder>".'
    required: false
    default: all

  onlyAnnotateModifiedLines:
    description: Only post annotations on lines that have changed within a PR.
    required: false
    default: 'false'

  debug:
    description: 'Log debugging information to stdout'
    required: false
    default: 'false'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.version }}
    - ${{ inputs.files }}
    - ${{ inputs.onlyAnnotateModifiedLines }}
    - ${{ inputs.debug }}
